### ISSUE TITLE
Hibernate 5.1 series support

### ISSUE THREAD

**Issue by larshelge** [mihaicostin/hibernate-l2-memcached#8]
Are there any plans for support Hibernate 5.1 series?

We are on Hibernate version 5.1.5. When using hibernate-l2-memcached version 5.0.1.0 we get this exception during startup:

``
Caused by: java.lang.IncompatibleClassChangeError: Expected static method org.hibernate.cache.internal.DefaultCacheKeysFactory.createEntityKey(Ljava/lang/Object;Lorg/hibernate/persister/entity/EntityPersister;Lorg/hibernate/engine/spi/SessionFactoryI
	at com.mc.hibernate.memcached.strategy.ReadWriteMemcachedEntityRegionAccessStrategy.generateCacheKey(ReadWriteMemcachedEntityRegionAccessStrategy.java:113)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:184)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:125)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1139)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:998)
	at org.hibernate.loader.Loader.doQuery(Loader.java:936)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2622)
	at org.hibernate.loader.Loader.listUsingQueryCache(Loader.java:2464)
	at org.hibernate.loader.Loader.list(Loader.java:2426)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:385)
``

When using hibernate-l2-memcached version 5.2.1.0 we get this exception during startup:

``
Caused by: java.lang.AbstractMethodError: com.mc.hibernate.memcached.region.MemcachedQueryResultsRegion.get(Lorg/hibernate/engine/spi/SessionImplementor;Ljava/lang/Object;)Ljava/lang/Object;
	at org.hibernate.cache.internal.StandardQueryCache.getCachedResults(StandardQueryCache.java:242)
	at org.hibernate.cache.internal.StandardQueryCache.get(StandardQueryCache.java:158)
	at org.hibernate.loader.Loader.getResultFromQueryCache(Loader.java:2546)
	at org.hibernate.loader.Loader.listUsingQueryCache(Loader.java:2454)
	at org.hibernate.loader.Loader.list(Loader.java:2426)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:385)
``

Would support for Hibernate 5.1 be feasible to implement?

**Comment by mihaicostin** [comment]
I've just released a new version *5.1.5.0* to maven central. It might take a couple of hours until it shows up.
Please let me know if you run into any other issues.

**Comment by larshelge** [comment]
This is fantastic! Our app starts normally using the new version. Thanks so much for the quick reply.
